apiVersion: v1
baseDomain: ms1.lan
compute:
  - hyperthreading: Enabled
    name: worker
    replicas: 0 # Must be set to 0 for User Provisioned Installation as worker nodes will be manually deployed.
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: okd # Cluster name
networking:
  networkType: OVNKubernetes
  machineNetwork:
    - cidr: 10.0.0.0/24
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - 172.30.0.0/16
platform:
  none: {}
fips: false
pullSecret: '<your-pullsecret-from-redhat-site>'
sshKey: '<your-ssh-key>'
